# Generated by Django 3.2 on 2021-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_remove_client_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
