# Generated by Django 3.2 on 2021-07-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_client_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
