# Generated by Django 3.2 on 2021-07-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
